### ISSUE TITLE
Customize display of InstanceItem in the tree view.

### ISSUE THREAD

**Issue by phtaylor** [ZeaInc/zea-tree-view#22]
A part may occur multiple times within an 'assembly'.

Each time a part occurs, it is nested under an InstanceItem

Part: Wheel
Instance: LeftWheel

> LeftWheel (InstanceItem) 
   > Wheel (Part)

> LeftWheel (InstanceItem of Part) 

We do not display the Reference item in the tree.

https://github.com/ZeaInc/zea-tree-view/blob/main/src/index.ts#L174-L200

https://github.com/ZeaInc/zea-tree-view/blob/main/src/index.ts#L371-L381

https://github.com/ZeaInc/zea-tree-view/blob/main/src/index.ts#L841-L845

https://github.com/ZeaInc/zea-tree-view/blob/main/src/index.ts#L841-L845

https://docs.google.com/document/d/1k0pWrgCqZ5RhLoHrshieqTCfiojAR3XZESUT-NRORnE/edit#heading=h.1srivdei8oo0

**Comment by mauroporras** [comment]
Also, bring back the tooltip.
